- hosts: wp
  vars_files:
    - wordpress_vars.yaml
  tasks:
    - yum:
        name: '{{ php["remi_repo"]["pkg"] }}'
        state: present
        validate_certs: no
    - yum_repository:
        name: remi-safe
        file: remi-safe
        mirrorlist: '{{ php["remi_repo"]["safe_mirror"] }}'
        description: remi-safe 
        enabled: no
    - yum_repository:
        name: remi-php74
        file: remi-php74
        mirrorlist: '{{ php["remi_repo"]["php74_mirror"] }}'
        description: remi-php74 
        enabled: yes
        gpgcheck: yes
        gpgkey: '{{ php["remi_repo"]["gpgkey_path"] }}'
    - yum:
        name: "{{ wp_pkg }}"
        state: installed
    - service:
        name: httpd 
        state: started 
        enabled: yes
    - service:
        name: mariadb
        state: started
        enabled: yes
    - get_url:
        url: '{{ wp_source_url }}'
        dest: /home/vagrant
    - unarchive:
        src: '/home/vagrant/{{ wp_file_name }}'
        remote_src: yes 
        dest: /var/www/html 
        owner: apache 
        group: apache
    - mysql_db:
        name: '{{ mysql["dbname"] }}'
        state: present 
        login_user: root
    - mysql_user:
        name: '{{ mysql["dbuser"] }}' 
        password: '{{ mysql["dbpwd"] }}' 
        state: present 
        login_user: root 
        priv: '{{ mysql["dbname"] }}.*:ALL'
    - copy:
        src: /var/www/html/wordpress/wp-config-sample.php 
        remote_src: yes 
        dest: /var/www/html/wordpress/wp-config.php 
        owner: apache 
        group: apache
    - template:
        src: wp-config.php.j2
        dest: /var/www/html/wordpress/wp-config.php

