- hosts: all
  tasks:
    - command: sudo amazon-linux-extras install -y lamp-mariadb10.2-php7.2 php7.2
    - yum:
        name: https://rpms.remirepo.net/enterprise/remi-release-7.rpm
        state: present
        validate_certs: no
    - yum_repository:
        name: remi-safe
        file: remi-safe
        mirrorlist: http://cdn.remirepo.net/enterprise/7/safe/mirror
        description: remi-safe
        enabled: no
    - yum_repository:
        name: remi-php74
        file: remi-php74
        mirrorlist: http://cdn.remirepo.net/enterprise/7/php74/mirror
        description: remi-php74
        enabled: yes
        gpgcheck: yes
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-remi
    - yum:
        name: httpd,php,php-mysqlnd,mariadb,mariadb-server,python2-PyMySQL
        state: installed
    - service:
        name: httpd
        state: started
        enabled: yes
    - service:
        name: mariadb
        state: started
        enabled: yes
    - get_url:
        url: https://wordpress.org/wordpress-5.9.3.tar.gz
        dest: /home/ec2-user
    - unarchive:
        src: /home/ec2-user/wordpress-5.9.3.tar.gz
        remote_src: yes
        dest: /var/www/html
        owner: apache
        group: apache
    - mysql_db:
        name: wordpress
        state: present
        login_user: root
    - mysql_user:
        name: wordpress
        password: skdud3150
        state: present
        login_user: root
        priv: "wordpress.*:ALL"
    - copy:
        src: /var/www/html/wordpress/wp-config-sample.php
        remote_src: yes
        dest: /var/www/html/wordpress/wp-config.php
        owner: apache
        group: apache
    - replace:
        path: /var/www/html/wordpress/wp-config.php
        regexp: database_name_here
        replace: wordpress
    - replace:
        path: /var/www/html/wordpress/wp-config.php
        regexp: username_here
        replace: wordpress
    - replace:
        path: /var/www/html/wordpress/wp-config.php
        regexp: password_here
        replace: skdud3150
    - replace:
        path: /var/www/html/wordpress/wp-config.php
        regexp: localhost
        replace : rdsendpoint